# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EY2Wh6LdD-irA_zQoLykAz261glsvTu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

veriler = pd.read_csv('musteriler.csv')

X = veriler.iloc[:,3:].values

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, init = 'k-means++')
kmeans.fit(X)

print(kmeans.cluster_centers_)#clusterların merkezleri bulunur

sonuclar = []
for i in range(1,11):
  kmeans = KMeans(n_clusters= i, init='k-means++', random_state = 123) #her seferinde aynı random ile alsın
  #farklı cluster sayısını dene
  kmeans.fit(X)
  sonuclar.append(kmeans.inertia_)

print(sonuclar)

plt.plot(range(1,11),sonuclar) #segmentason noktaları gösterilir #wscc dusurmek icin ornek olarak 4 sec