# -*- coding: utf-8 -*-
"""random.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSxrqrhrv41uG-QWXxUyRdeDNHTE8cu5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

veriler = pd.read_csv('Ads_CTR_Optimisation.csv')

import random
N = 10000
d = 10
toplam = 0
secilenler = []
for i in range(0,N):
  ad = random.randrange(d) #rastgele bir sayı üret
  secilenler.append(ad)
  odul = veriler.values[ad] #n.satir 1 ise odul var yoksa 0 alır , bu calismadi odul = veriler.values[n,ad]
  toplam = toplam + odul

print(toplam)
plt.hist(secilenler)
plt.show()