# -*- coding: utf-8 -*-
"""keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jznLptJ0d24IVIEkjKMK2F5hXtiwQqPy
"""

pip install theano

pip install tensorflow

pip install keras

import tensorflow as tf
hello = tf.constant('Hello, Tensorflow')
print((hello))

#!/usr/bin/env python3
from cgi import test
import imp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#veriler alindi
veriler = pd.read_csv("Churn_Modelling.csv")
print(veriler)

X = veriler.iloc[:,3:13].values
Y = veriler.iloc[:,13].values
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
le2 = preprocessing.LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2])

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#aynı ANDA dönüştürme , farklı kolon yapılarını birleştri ve dönüştür
ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])],
                        remainder="passthrough"
)
X = ohe.fit_transform(X)
X = X[:,1:]


#eksik verileri doldur
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")


#donusum
from sklearn import preprocessing

from sklearn.model_selection import train_test_split #belli bir yere kadar deneme belli bir yerden sonra test olacak
#x bağımsız, y bapımlı değişken

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

#farkli dünyadaki veriler aynı dünyaya ekle
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_train)
print(x_test)

import keras
from keras.models import Sequential #ysa oluştur
from keras.layers import Dense

classifier = Sequential()#yapay sinir ağı oluştu
classifier.add(Dense(6, activation="relu", input_dim = 11))#dense kaç katman olacak, 6 gizli 11 giriş