# -*- coding: utf-8 -*-
"""tf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jznLptJ0d24IVIEkjKMK2F5hXtiwQqPy
"""

pip install theano

pip install tensorflow

pip install keras

import tensorflow as tf
hello = tf.constant('Hello, Tensorflow')
print((hello))