# -*- coding: utf-8 -*-
"""apyori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5cSz-kbUo1dXWZY5OsqgM3rkY1xBk8C
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

veriler = pd.read_csv('sepet.csv', header = None) #kolon başlığı yok

t = []
for i in range (0,7501):
  t.append([str(veriler.values[i,j]) for j in range(0,20)])

from apyori import apriori
kurallar = apriori(t,min_support=0.01, min_confidence=0.2, min_lift = 3, min_lenght = 2) #lenght kaç elemandan oluşacaktır
print(list(kurallar))