# -*- coding: utf-8 -*-
"""model_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13rFcNePuao_31veXN-elCZox6I4gp6gm
"""

import pandas as pd
url = "http://bilkav.com/satislar.csv"
veriler = pd.read_csv(url)
veriler = veriler.values
print(veriler)

X = veriler[:,0:1]
Y = veriler[:,1]

bolme = 0.33
from sklearn import model_selection
x_t,x_te,y_t,y_te = model_selection.train_test_split(X,Y,test_size = bolme)

"""
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_t,y_t)
print(lr.predict(x_te))
"""

import pickle
dosya = "mode.kayit" #dosyayı kaydet
#pickle.dump(lr,open(dosya,'wb')) #dump boşalt

yuklenen = pickle.load(open(dosya,'rb'))
print(yuklenen)
print(yuklenen.predict(x_te))